AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PDF to PowerPoint Converter API

Globals:
  Function:
    Timeout: 300
    MemorySize: 3008
    Runtime: python3.11
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  Environment:
    Type: String
    Default: prod
    Description: Environment name

Resources:
  PdfToPptxFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub pdf-to-pptx-converter-${Environment}
      CodeUri: .
      Handler: lambda_handler.lambda_handler
      Environment:
        Variables:
          LAMBDA_EXECUTION: "true"
          API_BASE_URL: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

Outputs:
  PdfToPptxApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
  
  PdfToPptxFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt PdfToPptxFunction.Arn
